# Generated by Django 3.0.8 on 2021-04-16 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('sub_category', models.CharField(max_length=50)),
                ('variety', models.CharField(max_length=50)),
                ('aln', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('pub_date', models.DateField()),
                ('image', models.FileField(null=True, upload_to='', verbose_name='')),
                ('farmer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Farmer')),
            ],
        ),
    ]
